version: unknown

core:
  image:
    repository: 
    tag: 
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

  replicaCount: 1

  extraEnv:
    PINEAPPLE_ENV_CHARTSDIR: /root/charts/environment

    PINEAPPLE_STORAGE_USER_QUOTA: "10000000000" # 10GB
    PINEAPPLE_PVC_CHARTSDIR: /root/charts/cephfs-pvc
    PINEAPPLE_PVC_CEPH_JSON_DIR: /root/config/cephfs-info.yaml

    # mongodb
    PINEAPPLE_MONGODB_URL: 
    PINEAPPLE_MONGODB_DATABASE: 

webterminal:
  replicaCount: 1
  image:
    repository: 
    tag: 
    pullPolicy: Always
  resources:
    server:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi
    gotty:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi

portal:
  replicaCount: 1

  image:
    repository: 
    tag: 
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

billing:
  replicaCount: 1

  image:
    repository: 
    tag: 
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

  mongodb:
    # required
    dbName:
    # required
    url:

  extraEnv:

webhook:
  image:
    repository: 
    tag: 
    pullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi
  port:
    containerPort: 8443
    servicePort: 443
  tls:
    cert: 
    key: 
    ca: 

rootCA: "pineapple-ca"

keycloak:
  clientID: pineapple
  url: 

harbor:
  url: 
  basepath: /api/v2.0
  basepathV1: /api
  storage: "50000000000" # 50G
  admin_username: 
  admin_password: 

userCeph:
  cephfs:
    monitors:
    path: 
    user: 
  cephSecret:
    key: 

webserverCeph:
  cephfs:
    monitors:
    path: 
    user: 
  cephSecret:
    key: 
  capacity:
    storage: 20Gi

expose:
  externalUsersDomain: 
  service:
    type: ClusterIP
    port: 80
  externalIngress:
    host: 
    tls:
      enable: false
      secretName: pineapple-tls
    url: 
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 1g
      nginx.ingress.kubernetes.io/proxy-buffer-size: 8k

tolerations: []

affinity: {}

nodeSelector: {}

appConf:
  ingressClass: nginx
