stages:
  - check
  - build_image
  - deploy

variables:
  IMAGE_NAME: '${IMAGE_REGISTRY}/openaios'

static_check:
  stage: check
  image: '${BUILD_IMAGE}'
  script:
    - make lint
    - make vet

.build_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  script:
    - >
      docker build -t ${IMAGE_TAG}
      --build-arg BUILDBASE=${BUILD_IMAGE}
      --build-arg KUBECTLBASE=${KUBECTL_IMAGE}
      --build-arg TARGETBASE=${TARGET_IMAGE}
      --build-arg VERSION=${VERSION}
      --build-arg GOPROXY=${GOPROXY} -f ./dockerfile/Dockerfile .
    - docker push ${IMAGE_TAG}

build_dev_image:
  extends: .build_image
  variables:
    IMAGE_TAG: ${IMAGE_NAME}:${CI_COMMIT_SHA}
    VERSION: ${CI_COMMIT_RREF_NAME}-${CI_COMMIT_SHA}
  only:
    - master

build_release_image:
  extends: .build_image
  variables:
    IMAGE_TAG: ${IMAGE_NAME}:${CI_COMMIT_TAG}
    VERSION: ${CI_COMMIT_TAG}-${CI_COMMIT_SHA}
  only:
    - tags 

.deploy:
  stage: deploy
  image: '${HELM_IMAGE}'
  variables:
    RELEASE_NAME: pineapple
    EXTRA_ARGS: ''
  script:
    - >
      helm upgrade --install ${RELEASE_NAME} ./charts/pineapple
      -n pineapple
      -f /secrets/openaios-values.yaml
      --set core.image.repository=${IMAGE_NAME}
      --set core.image.tag=${IMAGE_TAG}
      --set webterminal.image.repository=${IMAGE_NAME}
      --set webterminal.image.tag=${IMAGE_TAG}
      --set billing.image.repository=${IMAGE_NAME}
      --set billing.image.tag=${IMAGE_TAG}
      --set webhook.image.repository=${IMAGE_NAME}
      --set webhook.image.tag=${IMAGE_TAG}
      ${EXTRA_ARGS}

deploy_develop:
  extends: .deploy
  variables:
    IMAGE_TAG: ${CI_COMMIT_SHA}
  environment:
    name: pineapple-develop
  only:
    - master
  tags:
    - deploy-test

deploy_pre_product:
  extends: .deploy
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
    EXTRA_ARGS: "--wait --timeout=30m"
  environment:
    name: pineapple-develop
  only:
    - tags
  tags:
    - deploy-test

deploy_product:
  extends: .deploy
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  environment:
    name: pineapple-product
  only:
    - tags
  tags:
    - deploy-product
  when: manual

