stages:
  - check
  - build_image

variables:
  IMAGE_NAME: '${IMAGE_REGISTRY}/openaios'

static_check:
  stage: check
  image: '${BUILD_IMAGE}'
  script:
    - make lint
    - make vet

build_dev_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${IMAGE_NAME}:${CI_COMMIT_SHA}
    - VERSION=${CI_COMMIT_RREF_NAME}-${CI_COMMIT_SHA}
  script:
    - >
      docker build -t ${IMAGE_TAG}
      --build-arg BUILDBASE=${BUILD_IMAGE}
      --build-arg KUBECTLBASE=${KUBECTL_IMAGE}
      --build-arg TARGETBASE=${TARGET_IMAGE}
      --build-arg --build-arg VERSION=${VERSION}
      --build-arg GOPROXY=${GOPROXY} -f ./dockerfile/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - master

build_release_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${IMAGE_NAME}:${CI_COMMIT_TAG}
    - VERSION=${CI_COMMIT_TAG}-${CI_COMMIT_SHA}
  script:
    - docker build -t ${IMAGE_TAG} --build-arg VERSION=${VERSION} --build-arg GOPROXY=${GOPROXY} -f ./dockerfile/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - tags 
