stages:
  #- check
  #- build
  - build_image

variables:
  CORE_IMAGE: '${IMAGE_REGISTRY}/core'
  BILLING_IMAGE: '${IMAGE_REGISTRY}/billing'
  PORTAL_IMAGE: '${IMAGE_REGISTRY}/portal'
  WEBTERMINAL_IMAGE: '${IMAGE_REGISTRY}/webterminal'
  WEBHOOK_IMAGE: '${IMAGE_REGISTRY}/webhook'
  DIND_IMAGE: "docker.4pd.io/build:11.0"

#static_check:
#  stage: check
#  image: golang:1.16.6-buster
#  script:
#    - make lint
#    - make vet

build_core_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${CORE_IMAGE}:${CI_COMMIT_SHA}
  script:
    - docker build -t ${IMAGE_TAG} -f ./dockerfile/webserver/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - master

build_billing_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${BILLING_IMAGE}:${CI_COMMIT_SHA}
  script:
    - docker build -t ${IMAGE_TAG} -f ./dockerfile/billing-server/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - master

build_webterminal_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${WEBTERMINAL_IMAGE}:${CI_COMMIT_SHA}
  script:
    - docker build -t ${IMAGE_TAG} -f ./dockerfile/webterminal/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - master

build_webhook_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${WEBHOOK_IMAGE}:${CI_COMMIT_SHA}
  script:
    - docker build -t ${IMAGE_TAG} -f ./dockerfile/webhook/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - master
