stages:
  #- check
  #- build
  - build_image

variables:
  IMAGE_NAME: '${IMAGE_REGISTRY}/openaios'

#static_check:
#  stage: check
#  image: golang:1.16.6-buster
#  script:
#    - make lint
#    - make vet

build_image:
  stage: build_image
  image: '${DIND_IMAGE}'
  before_script:
    - IMAGE_TAG=${IMAGE_NAME}:${CI_COMMIT_SHA}
  script:
    - docker build -t ${IMAGE_TAG} --build-arg GOPROXY=${GOPROXY} -f ./dockerfile/Dockerfile .
    - docker push ${IMAGE_TAG}
  only:
    - master