apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pineapple.core.fullname" . }}-cephfs
  labels:
    {{- include "pineapple.core.labels" . | nindent 4 }}
data:
  key: {{ .Values.webserverCeph.cephSecret.key }}
