apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pineapple.billing.fullname" . }}-{{ .Release.Namespace }}-view
  labels:
    {{- include "pineapple.billing.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "pineapple.billing.fullname" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
