apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pineapple.billing.fullname" . }}
  labels:
    {{- include "pineapple.billing.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pineapple.billing.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}