apiVersion: v1
kind: Service
metadata:
  name: {{ include "pineapple.billing.fullname" . }}
  labels:
    {{- include "pineapple.billing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
  selector:
    {{- include "pineapple.billing.selectorLabels" . | nindent 4 }}
