openapi: 3.0.3
info:
  title: Pineapple-internal
  description: Pineapple internal api
  version: 0.0.1

servers:
  - url: "http://127.0.0.1:1234/internal-api"

security:
  - OpenID:
      - openid
      - email
      - profile
  - ApiKeyAuth: []

tags:
  - name: releases
  - name: finished

paths:
  /releases:
    delete:
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: userID
      tags:
        - releases
        - finished
      summary: Delete all releases
      operationId: deleteReleases
      responses:
        200:
          description: OK
        400:
          description: Error
        500:
          $ref: "#/components/responses/ServerError"

components:
  responses:
    ServerError:
      description: server error
      content:
        text/plain:
          schema:
            type: string
          example: "Something went wrong."
    RequestError:
      description: http request error
      content:
        application/json:
          schema:
            type: object
            properties:
              content:
                type: object
              message:
                type: string
              type:
                type: string
    500:
      description: internal error
      content:
        text/plain:
          schema:
            type: string
          example: "internal error"
    400:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
              type:
                type: string
              content:
                type: object
            example:
              message: this request is bad
    401:
      description: Unauthorized
      content:
        text/plain:
          schema:
            type: string
