apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pineapple.webhook.fullname" . }}
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: {{ include "pineapple.webhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
    objectSelector:
      matchExpressions:
      - key: 4pd.io/openaios-webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
