apiVersion: v1
kind: Secret
metadata:
  name: pineapple-webhook-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webhook.tls.cert | nindent 4 }}
  tls.key: {{ .Values.webhook.tls.key | nindent 4 }}
