apiVersion: v1
kind: Secret
metadata:
  name: pineapple-webhook-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .Values.webhook.tls.cert | indent 4 }}
  tls.key: |
{{ .Values.webhook.tls.key | indent 4 }}