apiVersion: v1
kind: PersistentVolume
metadata:
  name: pineapple-{{ .Values.userId }}-pv
  labels:
    app: cephfs
    role: pv
    name: {{ .Release.Name }}
    user: {{ .Values.userId }}
spec:
  storageClassName: "ceph-storage"
  claimRef:
    name: remote-storage
    namespace: {{ .Values.userId }}
  capacity:
    storage: {{ .Values.capacity.storage }}
  accessModes:
    - ReadWriteMany
  cephfs:
    {{- toYaml .Values.cephfs | nindent 4 }}
    secretRef:
      name: pineapple-ceph-secret
