version: unknown

core:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

  replicaCount: 1

  extraEnv:
    PINEAPPLE_ENV_CHARTSDIR: ""

    PINEAPPLE_STORAGE_USER_QUOTA: "10000000000" # 10GB

    # mongodb
    PINEAPPLE_MONGODB_URL: ""
    PINEAPPLE_MONGODB_DATABASE: ""

webterminal:
  resources:
    server:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi
    gotty:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi

  replicaCount: 1

portal:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

  replicaCount: 1

billing:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi

  replicaCount: 1

  mongodb:
    dbName: ""
    url: ""

  extraEnv:

keycloak:
  clientID: ""
  url: ""

harbor:
  url: ""
  storage: "50000000000" # 50G
  admin_username: ""
  admin_password: ""

userCeph:
  cephfs:
    monitors: []
    path: ""
    user: ""
  cephSecret:
    key: ""

webserverCeph:
  cephfs:
    monitors: ""
    path: ""
    user: ""
  cephSecret:
    key: ""
  capacity:
    storage: 20Gi

webhook:
  tls:
    cert: ""
    key: ""
    ca: ""
expose:
  externalUsersDomain: ""
  service:
    type: ClusterIP
    port: 80
  externalIngress:
    host: ""
    tls:
      enable: true
      secretName: ""
    url: ""
    annotations:
      cert-manager.io/cluster-issuer: ""
      kubernetes.io/ingress.class: ""
      nginx.ingress.kubernetes.io/proxy-body-size: ""
      nginx.ingress.kubernetes.io/proxy-buffer-size: ""

appConf:
  ingressClass: ""
  externalDomain: ""
