apiVersion: v1
kind: Secret
metadata:
  name: {{ include "environment.fullname" . }}
  labels:
    {{- include "environment.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.serverType.ssh "True" }}
  ssh-key: |
    {{ required "sshKey is required!" .Values.ssh.sshKey }}
  {{- end }}
  jupyter-token: |
    {{ .Values.jupyter.token }}
