apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "environment.fullname" . }}-info
  labels:
    {{- include "environment.labels" . | nindent 4 }}
data:
  releaseInfo: |
    PINEAPPLE_ENV_INFO_START_HERE<<<
    {
      "name": "{{ .Release.Name }}",
      "create_tm": "",
      "environmentConfig": {
        "image": {
          "repository": "{{ .Values.image.repository }}",
          "tag": "{{ .Values.image.tag }}"
        },
        "mounts": {{ toJson .Values.volumeMounts }},
        "compute_unit": "{{ .Values.pineapple.default.resourceId }}",
        "ssh": {
          "enable": {{ .Values.serverType.ssh | lower }},
          "id_rsa.pub": {{ .Values.ssh.sshKey | quote }}
        },
        "jupyter": {
          "enable": {{ .Values.serverType.jupyter | lower }},
          "token": {{ .Values.jupyter.token | quote }}
        }
      },
      "notebook_url": "/ingress/{{ .Release.Namespace }}/env/{{ .Release.Name }}/jupyterlab"
    }
    <<<PINEAPPLE_ENV_INFO_END_HERE
