apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "environment.fullname" . }}
  labels:
    {{- include "environment.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    if [ ${USE_SSH} = "True" ]; then
      mkdir /run/sshd
      if [ ! -f /etc/ssh/ssh_host_rsa_key ] || [ ! -f /etc/ssh/ssh_host_ecdsa_key ] || [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
        ssh-keygen -A
      fi
      CAT_PATH=$(which cat)
      /usr/sbin/sshd \
      -o "AuthorizedKeysCommand ${CAT_PATH} /pineapple/secret/ssh/ssh-key" \
      -o "AuthorizedKeysCommandUser root"
      if [ $? -ne 0 ]; then
        echo "ERROR: ssh start failed!"
        exit 1
      fi
    fi
    if [ ${USE_JUPYTER} = "True" ]; then
      exec jupyter-lab --debug --no-browser \
      --ip="0.0.0.0" \
      --port=8888 \
      --allow-root \
      {{- if .Values.jupyter.token }}
      --LabApp.token={{ .Values.jupyter.token | quote }} \
      {{- else }}
      --LabApp.token='' \
      {{- end }}
      --LabApp.password='' \
      --LabApp.base_url="/ingress/{{ .Release.Namespace }}/env/{{ .Release.Name }}/jupyterlab"
    elif [ ${USE_JUPYTER} = "False" ]; then
      exec tail -f /dev/null
    fi