apiVersion: v2
name: alcide-advisor-cronjob
description: Alcide Advisor CronJob
keywords:
  - security
  - vulnerability scan
  - guardrails
type: application
version: 2.1.0
appVersion: 2.11.1
home: https://www.alcide.io
icon: https://www.alcide.io/wp-content/uploads/2020/01/advisor@3x.png
sources:
- https://github.com/alcideio/advisor
- https://github.com/alcideio/pipeline
maintainers:
- email: gadi@alcide.io
  name: gadinaor
