name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: make lint
      - run: make vet

  docker:
    runs-on: ubuntu-latest
    #services:
    #  registry:
    #    image: registry:2
    #    ports:
    #      - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build
        run: >
          docker build -t openaios:${GITHUB_SHA}
          --build-arg VERSION=${VERSION} -f ./dockerfile/Dockerfile .
