name: release

on:
  push:
    tags:
      - '*'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build and push
        run: |
          docker build -t 4pdosc/openaios:${BRANCH_NAME} \
            --build-arg VERSION=${BRANCH_NAME} \
            -f ./dockerfile/Dockerfile .
          docker push 4pdosc/openaios:${BRANCH_NAME}
          docker tag 4pdosc/openaios:${BRANCH_NAME} 4pdosc/openaios:latest
          docker push 4pdosc/openaios:latest
